using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Simcompanies_Price_Calculator.Entities {
    public static class MarketIndex {

        /// <summary>
        /// Generates a dictionary with marketId, marketName
        /// </summary>
        /// <returns></returns>
        public static Dictionary<int, string> GenerateIndex() {
            var index = new Dictionary<int, string>();
            index[1] = "Power";
            index[2] = "Water";
            index[3] = "Apples";
            index[4] = "Oranges";
            index[5] = "Grapes";
            index[6] = "Grain";
            index[7] = "Steak";
            index[8] = "Sausages";
            index[9] = "Eggs";
            index[10] = "Crude Oil";
            index[11] = "Petrol";
            index[12] = "Diesel";
            index[13] = "Transport";
            index[14] = "Minerals";
            index[15] = "Bauxite";
            index[16] = "Silicon";
            index[17] = "Chemicals";
            index[18] = "Aluminium";
            index[19] = "Plastic";
            index[20] = "Processors";
            index[21] = "Electronic Components";
            index[22] = "Batteries";
            index[23] = "Displays";
            index[24] = "Smart Phones";
            index[25] = "Tablets";
            index[26] = "Laptops";
            index[27] = "Monitors";
            index[28] = "Televisions";
            index[29] = "Plant Research";
            index[30] = "Energy Research";
            index[31] = "Mining Research";
            index[32] = "Electronics Research";
            index[33] = "Breeding Research";
            index[34] = "Chemistry Research";
            index[35] = "Software";
            index[40] = "Cotton";
            index[41] = "Fabric";
            index[42] = "Iron ore";
            index[43] = "Steel";
            index[44] = "Sand";
            index[45] = "Glass";
            index[46] = "Leather";
            index[47] = "On-board Computer";
            index[48] = "Electric Motor";
            index[49] = "Luxury Car Interior";
            index[50] = "Basic Interior";
            index[51] = "Car Body";
            index[52] = "Combustion Engine";
            index[53] = "Economy E-car";
            index[54] = "Luxury E-car";
            index[55] = "Economy car";
            index[56] = "Luxury car";
            index[57] = "Truck";
            index[58] = "Automotive Research";
            index[59] = "Fasion Research";
            index[60] = "Underwear";
            index[61] = "Gloves";
            index[62] = "Dress";
            index[63] = "Stiletto Heel";
            index[64] = "Handbags";
            index[65] = "Sneakers";
            index[66] = "Seeds";
            index[67] = "Xmas Crackers";
            index[68] = "Gold Ore";
            index[69] = "Golden Bars";
            index[70] = "Luxary Watch";
            index[71] = "Necklace";
            index[72] = "Sugarcane";
            index[73] = "Ethanol";
            index[74] = "Methane";
            index[75] = "Carbon Fibers";
            index[76] = "Carbon Composite";
            index[77] = "Fuselage";
            index[78] = "Wing";
            index[79] = "HighGrade E-Comps";
            index[80] = "Flight Computer";
            index[81] = "Cockpit";
            index[82] = "Attitude Control";
            index[83] = "Rocket Fuel";
            index[84] = "Propellant Tank";
            index[85] = "Solid Fuel Booster";
            index[86] = "Rocket Engine";
            index[87] = "Heat Shield";
            index[88] = "Ion Drive";
            index[89] = "Jet Engine";
            index[90] = "Sub-orbital 2cd Stage";
            index[91] = "Sub-orbital Rocket";
            index[92] = "Orbital booster";
            index[93] = "Starship";
            index[94] = "BFR";
            index[95] = "Jumbo Jet";
            index[96] = "Luxury Jet";
            index[97] = "Single engine plane";
            index[98] = "Quadcopter";
            index[99] = "Satelite";
            index[100] = "Aerospace Research";
            index[101] = "Reinforced Concrete";
            index[102] = "Bricks";
            index[103] = "Cement";
            index[104] = "Clay";
            index[105] = "Limestone";
            index[106] = "Wood";
            index[107] = "Steel beams";
            index[108] = "Planks";
            index[109] = "Windows";
            index[110] = "Tools";
            index[111] = "Construction Units";
            index[112] = "Bulldozer";
            index[113] = "Materials Research";
            index[114] = "Robots";
            index[115] = "Cows";
            index[116] = "Pigs";
            index[117] = "Milk";
            index[118] = "Coffee Beans";
            index[119] = "Coffee Powder";
            index[120] = "Vegetables";
            index[121] = "Bread";
            index[122] = "cheese";
            index[123] = "Apple Pie";
            index[124] = "Orange Juice";
            index[125] = "Apple Cider";
            index[126] = "Ginger Beer";
            index[127] = "Frozen Pizza";
            index[128] = "Pasta";
            index[129] = "Hamburger";
            index[130] = "Lasagna";
            index[131] = "Meatballs";
            index[132] = "Cocktails";
            index[133] = "Flour";
            index[134] = "Butter";
            index[135] = "Sugar";
            index[136] = "Cocoa";
            index[137] = "Dough";
            index[138] = "Sauce";
            index[139] = "Fodder";
            index[140] = "Ramadan Sweets";
            index[141] = "Vegetable Oil";
            index[142] = "Salad";
            index[143] = "Samosa";
            index[144] = "Xmas ornaments";
            index[145] = "Recipes";

            return index;
        }
    }
}
